%Author: Lucas Encarnacion-Rivera
%contact: lencarn@emory.edu
%                        Fiber Morphometry and Data Extraction
%  this script processes data from imagej --> Specifically it acquires the
%  mean area, feret, places these values into an array, indexes and
%  classifies fibers by type, and saves these variables from the workspace
%  to the computer for later retrieval

%%
%Start by importing all the excel files generated by myosoft. 
%%
% Plug in the gates that you want to use where IG is "Intensity gate" and A
% is type IIA, B is type IIB, and I is type I

AIG = 15310;
BIG = 9120;
IIG = 6000;

%%
fiberstats.area = FiberareaResults(:,2);  
fiberstats.feret = FiberareaResults(:,18);

MeanA = mean(fiberstats.area.Area);
MeanF = mean(fiberstats.feret.Feret);
figure
histogram(fiberstats.area.Area, 30)
title('Area in microns^2');
figure
histogram(fiberstats.feret.Feret, 30)
title('Feret in microns^2');
%%
fiberstats_IIB.meanInt = FibertypeResultstypeIIb(:,3);  
figure
histfit(fiberstats_IIB.meanInt.Mean, 30, 'kernel')
title('Distribution of Mean Intensity IIb');

fiberstats_I.meanInt = FibertypeResultstypeI(:,3);  
figure
histfit(fiberstats_I.meanInt.Mean, 30, 'kernel')
title('Distribution of Mean Intensity I');

fiberstats_IIa.meanInt = FibertypeResultstypeIIa(:,3);
figure
histfit(fiberstats_IIa.meanInt.Mean, 30, 'kernel')
title('Distribution of Mean Intensity IIa'); 
%% 
fiberstats_IIB.StdDevInt = FibertypeResultstypeIIb(:,4);  
fiberstats_IIB.modeInt = FibertypeResultstypeIIb(:,5);  
fiberstats_IIB.minInt = FibertypeResultstypeIIb(:,6);  
fiberstats_IIB.maxInt = FibertypeResultstypeIIb(:,7); 

fibMintB = fiberstats_IIB.meanInt.Mean;

type_IIB_pos = fibMintB > BIG; 
type_IIB_neg = fibMintB < BIG;
type_IIB_pos_indx = find(type_IIB_pos);
type_IIB_neg_indx = find(type_IIB_neg);
%%
fiberstats_I.StdDevInt = FibertypeResultstypeI(:,4);  
fiberstats_I.modeInt = FibertypeResultstypeI(:,5);  
fiberstats_I.minInt = FibertypeResultstypeI(:,6);  
fiberstats_I.maxInt = FibertypeResultstypeI(:,7);  

fibMintI = fiberstats_I.meanInt.Mean;

type_I_pos = fibMintI > IIG; 
type_I_neg = fibMintI < IIG;
type_I_pos_indx = find(type_I_pos);
type_I_neg_indx = find(type_I_neg);
%%
fiberstats_IIa.StdDevInt = FibertypeResultstypeIIa(:,4);  
fiberstats_IIa.modeInt = FibertypeResultstypeIIa(:,5);  
fiberstats_IIa.minInt = FibertypeResultstypeIIa(:,6);  
fiberstats_IIa.maxInt = FibertypeResultstypeIIa(:,7);  

fibMintA = fiberstats_IIa.meanInt.Mean;

type_IIA_pos = fibMintA > AIG; 
type_IIA_neg = fibMintA < AIG;
type_IIA_pos_indx = find(type_IIA_pos);
type_IIA_neg_indx = find(type_IIA_neg);
%%
IIaMult = type_IIA_pos*4;
IMult = type_I_pos*1;
IIbMult = type_IIB_pos*6;
%%
FibTArr = [IIaMult,IMult,IIbMult];
FibSum = [sum(FibTArr(:,[1 2 3]),2)];

fibIIxlog = FibSum < 1;
FibIIX_indx = find(fibIIxlog);

%%
IIa_plus_IIb_log = FibSum==10;
IIa_plus_I_log = FibSum==5;
IIb_plus_I_log = FibSum==7;

Mixed_Fiber_Types.IIa_plus_IIb = find(IIa_plus_IIb_log);  
Mixed_Fiber_Types.IIa_plus_I = find(IIa_plus_I_log);
Mixed_Fiber_Types.IIb_plus_I = find(IIb_plus_I_log);

%% 
FibArea = table2array(fiberstats.area);
Fiber_Area_Distribution.IIa_Area = FibArea([type_IIA_pos_indx]);
Fiber_Area_Distribution.IIb_Area = FibArea([type_IIB_pos_indx]);
Fiber_Area_Distribution.I_Area = FibArea([type_I_pos_indx]);
Fiber_Area_Distribution.IIX_Area = FibArea([FibIIX_indx]);

Fiber_Area_Distribution.IIa_IIb_Area = FibArea([Mixed_Fiber_Types.IIa_plus_IIb]);
Fiber_Area_Distribution.IIa_I_Area = FibArea([Mixed_Fiber_Types.IIa_plus_I]);
Fiber_Area_Distribution.IIb_I_Area = FibArea([Mixed_Fiber_Types.IIb_plus_I]);

%% 
numFibs = numel(FibArea);
numI = numel(type_I_pos_indx);
numIIb = numel(type_IIB_pos_indx);
numIIa = numel(type_IIA_pos_indx);
numIIx = numel(FibIIX_indx);

Fiber_Type_Proportion.I_Proportion = numI/numFibs;
Fiber_Type_Proportion.IIb_Proportion = numIIb/numFibs;
Fiber_Type_Proportion.IIa_Proportion = numIIa/numFibs;
Fiber_Type_Proportion.IIX_Proportion = numIIx/numFibs;
%%
% instert correct directory and then comment out the code (eliminate '%') 
% save('C:\cell outlining training files\data\Processed Image Data\ fiber size and type data')